#!/usr/bin/env python3
"""
Reanalyze severe-gap properties and insert fresh rows into chamgab_analyses.

Input:
- CSV generated by scripts/audit_chamgab_gap_full.py
  (expects columns: property_id, abs_gap_pct, ...)

Flow:
1) Read property IDs where abs_gap_pct >= threshold.
2) Predict via local ModelService.
3) Insert new chamgab_analyses rows.
4) Optionally write chamgab_analysis_events.
"""

from __future__ import annotations

import argparse
import csv
import os
import pickle
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional
from uuid import UUID

from supabase import create_client


ROOT = Path(__file__).resolve().parents[1]
ML_API_DIR = ROOT / "ml-api"
ML_ENV_PATH = ML_API_DIR / ".env"
MODELS_DIR = ML_API_DIR / "app" / "models"


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            if k.strip() and not os.environ.get(k.strip()):
                os.environ[k.strip()] = v.strip()


def latest_severe_csv(logs_dir: Path) -> Optional[Path]:
    files = sorted(logs_dir.glob("chamgab_gap_audit_severe25_*.csv"))
    return files[-1] if files else None


def load_target_property_ids(
    csv_path: Path,
    threshold: float,
    limit: int,
) -> List[str]:
    out: List[str] = []
    seen = set()
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            pid = (row.get("property_id") or "").strip()
            if not pid or pid in seen:
                continue
            try:
                abs_gap = float(row.get("abs_gap_pct") or 0)
            except ValueError:
                continue
            if abs_gap < threshold:
                continue
            seen.add(pid)
            out.append(pid)
            if limit > 0 and len(out) >= limit:
                break
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--csv",
        type=str,
        default="",
        help="Severe audit CSV path. If empty, latest severe25 csv in logs/ is used.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=25.0,
        help="abs_gap_pct threshold to include target properties.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Limit number of properties to process (0 = all).",
    )
    parser.add_argument(
        "--sleep-ms",
        type=int,
        default=0,
        help="Sleep between inserts to reduce write burst.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only list targets, do not write analyses.",
    )
    args = parser.parse_args()

    load_env_file(ML_ENV_PATH)
    supabase_url = os.environ.get("SUPABASE_URL")
    supabase_key = os.environ.get("SUPABASE_SERVICE_KEY")
    if not supabase_url or not supabase_key:
        print("ERROR: SUPABASE_URL / SUPABASE_SERVICE_KEY not set")
        return 2

    csv_path = Path(args.csv) if args.csv else None
    if not csv_path:
        csv_path = latest_severe_csv(ROOT / "logs")
    if not csv_path or not csv_path.exists():
        print("ERROR: severe csv not found")
        return 2

    target_ids = load_target_property_ids(
        csv_path=csv_path,
        threshold=args.threshold,
        limit=args.limit,
    )
    if not target_ids:
        print("No target properties found.")
        return 1

    print(f"CSV: {csv_path}")
    print(f"Targets (abs_gap>={args.threshold}%): {len(target_ids):,}")
    if args.dry_run:
        print("Dry-run mode. No DB writes.")
        return 0

    import sys

    sys.path.insert(0, str(ML_API_DIR))
    from app.services.model_service import ModelService

    with (MODELS_DIR / "xgboost_model.pkl").open("rb") as f:
        model = pickle.load(f)
    with (MODELS_DIR / "feature_artifacts.pkl").open("rb") as f:
        artifacts = pickle.load(f)
    residual = None
    residual_path = MODELS_DIR / "residual_info.pkl"
    if residual_path.exists():
        with residual_path.open("rb") as f:
            residual = pickle.load(f)

    service = ModelService(model, artifacts, residual)
    sb = create_client(supabase_url, supabase_key)

    print("Reanalyzing and inserting...")
    ok = 0
    failed = 0
    sleep_s = max(args.sleep_ms, 0) / 1000.0
    t0 = time.time()

    for idx, pid in enumerate(target_ids, start=1):
        try:
            pred = service.predict(UUID(pid))
            ins = {
                "property_id": pid,
                "user_id": None,
                "chamgab_price": pred["chamgab_price"],
                "min_price": pred["min_price"],
                "max_price": pred["max_price"],
                "confidence": pred["confidence"],
            }
            res = sb.table("chamgab_analyses").insert(ins).execute()
            analysis_id = None
            if res.data and len(res.data) > 0:
                analysis_id = res.data[0].get("id")
            try:
                sb.table("chamgab_analysis_events").insert(
                    {
                        "property_id": pid,
                        "analysis_id": analysis_id,
                        "actor_user_id": None,
                        "status": "success",
                        "http_status": 200,
                        "request": {
                            "source": "batch_reanalyze_severe_gap",
                            "threshold": args.threshold,
                            "csv": str(csv_path.name),
                            "at": datetime.now(timezone.utc).isoformat(),
                        },
                    }
                ).execute()
            except Exception:
                pass
            ok += 1
        except Exception as e:
            failed += 1
            try:
                sb.table("chamgab_analysis_events").insert(
                    {
                        "property_id": pid,
                        "analysis_id": None,
                        "actor_user_id": None,
                        "status": "error",
                        "http_status": 500,
                        "error_code": "BATCH_REANALYZE_ERROR",
                        "error_message": str(e)[:500],
                        "request": {
                            "source": "batch_reanalyze_severe_gap",
                            "threshold": args.threshold,
                            "csv": str(csv_path.name),
                        },
                    }
                ).execute()
            except Exception:
                pass

        if idx % 200 == 0 or idx == len(target_ids):
            elapsed = time.time() - t0
            print(
                f"  progress {idx:,}/{len(target_ids):,} "
                f"(ok={ok:,}, failed={failed:,}, elapsed={elapsed:.1f}s)"
            )
        if sleep_s > 0:
            time.sleep(sleep_s)

    elapsed = time.time() - t0
    print("Done.")
    print(f"  inserted={ok:,}, failed={failed:,}, elapsed={elapsed:.1f}s")
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
