#!/usr/bin/env python3
"""
Reanalyze severe-gap properties and insert fresh rows into chamgab_analyses.

Input:
- CSV generated by scripts/audit_chamgab_gap_full.py
  (expects columns: property_id, abs_gap_pct, ...)

Flow:
1) Read property IDs where abs_gap_pct >= threshold.
2) Predict via local ModelService.
3) Insert new chamgab_analyses rows.
4) Optionally write chamgab_analysis_events.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import pickle
import time
from datetime import datetime, timezone
from pathlib import Path
from statistics import median
from typing import Any, Dict, List, Optional, Tuple
from uuid import UUID

from supabase import create_client

from app.services.model_service import ModelService


ROOT = Path(__file__).resolve().parents[1]
ML_ENV_PATH = ROOT / ".env"
MODELS_DIR = ROOT / "app" / "models"
LOGS_DIR = ROOT / "logs"


def load_env_file(path: Path) -> None:
    if not path.exists():
        return
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            if k.strip() and not os.environ.get(k.strip()):
                os.environ[k.strip()] = v.strip()


def disable_proxy_env() -> None:
    for k in (
        "HTTP_PROXY",
        "HTTPS_PROXY",
        "ALL_PROXY",
        "http_proxy",
        "https_proxy",
        "all_proxy",
    ):
        if k in os.environ:
            os.environ[k] = ""


def latest_severe_csv(logs_dir: Path) -> Optional[Path]:
    files = sorted(logs_dir.glob("chamgab_gap_audit_severe25_*.csv"))
    return files[-1] if files else None


def _safe_float(value: Any) -> Optional[float]:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _price_bucket(tx_price: float) -> str:
    if tx_price < 100_000_000:
        return "lt_100m"
    if tx_price < 300_000_000:
        return "100m_300m"
    if tx_price < 700_000_000:
        return "300m_700m"
    return "gte_700m"


def load_target_rows(
    csv_path: Path,
    threshold: float,
    limit: int,
    min_tx_price: float,
) -> List[Dict[str, Any]]:
    out: List[Dict[str, Any]] = []
    seen = set()
    with csv_path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            pid = (row.get("property_id") or "").strip()
            if not pid or pid in seen:
                continue
            try:
                abs_gap = float(row.get("abs_gap_pct") or 0)
            except ValueError:
                continue
            if abs_gap < threshold:
                continue
            tx_price = _safe_float(row.get("tx_price"))
            if tx_price is None or tx_price < min_tx_price:
                continue
            ai_price = _safe_float(row.get("ai_price"))
            sigungu = (row.get("sigungu") or "").strip()
            seen.add(pid)
            out.append(
                {
                    "property_id": pid,
                    "sigungu": sigungu,
                    "tx_price": tx_price,
                    "ai_price": ai_price,
                    "abs_gap_pct": abs_gap,
                    "price_bucket": _price_bucket(tx_price),
                }
            )
            if limit > 0 and len(out) >= limit:
                break
    return out


def build_calibration_factors(
    target_rows: List[Dict[str, Any]],
    *,
    min_samples: int,
    clamp_low: float,
    clamp_high: float,
) -> Dict[str, Any]:
    grouped: Dict[Tuple[str, str], List[float]] = {}
    global_ratios: List[float] = []

    for row in target_rows:
        ai_price = _safe_float(row.get("ai_price"))
        tx_price = _safe_float(row.get("tx_price"))
        if ai_price is None or tx_price is None or ai_price <= 0 or tx_price <= 0:
            continue
        ratio = tx_price / ai_price
        if ratio <= 0:
            continue
        global_ratios.append(ratio)
        key = ((row.get("sigungu") or "").strip(), str(row.get("price_bucket") or ""))
        grouped.setdefault(key, []).append(ratio)

    if not global_ratios:
        return {"global": 1.0, "by_key": {}, "min_samples": min_samples}

    global_factor = float(median(global_ratios))
    global_factor = max(clamp_low, min(clamp_high, global_factor))

    by_key: Dict[str, float] = {}
    for key, values in grouped.items():
        if len(values) < max(1, min_samples):
            continue
        factor = float(median(values))
        factor = max(clamp_low, min(clamp_high, factor))
        by_key[f"{key[0]}::{key[1]}"] = round(factor, 4)

    return {
        "global": round(global_factor, 4),
        "by_key": by_key,
        "min_samples": max(1, min_samples),
        "clamp_low": clamp_low,
        "clamp_high": clamp_high,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--csv",
        type=str,
        default="",
        help="Severe audit CSV path. If empty, latest severe25 csv in logs/ is used.",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=25.0,
        help="abs_gap_pct threshold to include target properties.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=0,
        help="Limit number of properties to process (0 = all).",
    )
    parser.add_argument(
        "--min-tx-price",
        type=float,
        default=max(0.0, float(os.getenv("CHAMGAB_REANALYZE_MIN_TX_PRICE", "50000000"))),
        help="Exclude severe rows with tx_price below this threshold.",
    )
    parser.add_argument(
        "--calibration-min-samples",
        type=int,
        default=max(1, int(os.getenv("CHAMGAB_REANALYZE_CALIBRATION_MIN_SAMPLES", "5"))),
        help="Minimum samples per (sigungu, price_bucket) calibration key.",
    )
    parser.add_argument(
        "--calibration-clamp-low",
        type=float,
        default=max(0.1, float(os.getenv("CHAMGAB_REANALYZE_CALIBRATION_CLAMP_LOW", "0.7"))),
    )
    parser.add_argument(
        "--calibration-clamp-high",
        type=float,
        default=max(0.1, float(os.getenv("CHAMGAB_REANALYZE_CALIBRATION_CLAMP_HIGH", "1.3"))),
    )
    parser.add_argument(
        "--sleep-ms",
        type=int,
        default=0,
        help="Sleep between inserts to reduce write burst.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only list targets, do not write analyses.",
    )
    args = parser.parse_args()

    load_env_file(ML_ENV_PATH)
    disable_proxy_env()
    supabase_url = os.environ.get("SUPABASE_URL")
    supabase_key = os.environ.get("SUPABASE_SERVICE_KEY")
    if not supabase_url or not supabase_key:
        print("ERROR: SUPABASE_URL / SUPABASE_SERVICE_KEY not set")
        return 2

    csv_path = Path(args.csv) if args.csv else None
    if not csv_path:
        csv_path = latest_severe_csv(LOGS_DIR)
    if not csv_path or not csv_path.exists():
        print("ERROR: severe csv not found")
        return 2

    target_rows = load_target_rows(
        csv_path=csv_path,
        threshold=args.threshold,
        limit=args.limit,
        min_tx_price=max(0.0, float(args.min_tx_price)),
    )
    if not target_rows:
        print("No target properties found.")
        return 1
    target_ids = [str(row["property_id"]) for row in target_rows]

    calibration = build_calibration_factors(
        target_rows,
        min_samples=args.calibration_min_samples,
        clamp_low=min(args.calibration_clamp_low, args.calibration_clamp_high),
        clamp_high=max(args.calibration_clamp_low, args.calibration_clamp_high),
    )
    global_factor = float(calibration.get("global") or 1.0)
    factors_by_key = dict(calibration.get("by_key") or {})
    target_by_id = {str(row["property_id"]): row for row in target_rows}

    print(f"CSV: {csv_path}")
    print(f"Targets (abs_gap>={args.threshold}%): {len(target_ids):,}")
    print(
        "Calibration factors: "
        f"global={global_factor:.4f}, "
        f"grouped={len(factors_by_key):,}, "
        f"min_samples={calibration.get('min_samples')}"
    )
    if args.dry_run:
        summary = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "mode": "dry-run",
            "csv_path": str(csv_path),
            "threshold": args.threshold,
            "min_tx_price": float(args.min_tx_price),
            "targets": len(target_ids),
            "inserted": 0,
            "failed": 0,
            "elapsed_sec": 0.0,
            "calibration": calibration,
        }
        latest_summary_path = LOGS_DIR / "chamgab_reanalyze_summary_latest.json"
        latest_summary_path.write_text(
            json.dumps(summary, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        print(f"SUMMARY_JSON:{json.dumps(summary, ensure_ascii=False)}")
        return 0

    with (MODELS_DIR / "xgboost_model.pkl").open("rb") as f:
        model = pickle.load(f)
    with (MODELS_DIR / "feature_artifacts.pkl").open("rb") as f:
        artifacts = pickle.load(f)
    residual = None
    residual_path = MODELS_DIR / "residual_info.pkl"
    if residual_path.exists():
        with residual_path.open("rb") as f:
            residual = pickle.load(f)

    service = ModelService(model, artifacts, residual)
    sb = create_client(supabase_url, supabase_key)

    print("Reanalyzing and inserting...")
    ok = 0
    failed = 0
    calibrated = 0
    sleep_s = max(args.sleep_ms, 0) / 1000.0
    t0 = time.time()

    for idx, pid in enumerate(target_ids, start=1):
        target = target_by_id.get(pid) or {}
        sigungu = str(target.get("sigungu") or "").strip()
        price_bucket = str(target.get("price_bucket") or "")
        factor_key = f"{sigungu}::{price_bucket}"
        calibration_factor = float(factors_by_key.get(factor_key, global_factor))
        try:
            pred = service.predict(UUID(pid))
            raw_price = int(pred["chamgab_price"])
            raw_min = int(pred["min_price"])
            raw_max = int(pred["max_price"])
            adj_price = max(0, int(round(raw_price * calibration_factor)))
            adj_min = max(0, int(round(raw_min * calibration_factor)))
            adj_max = max(0, int(round(raw_max * calibration_factor)))
            if adj_min > adj_max:
                adj_min, adj_max = adj_max, adj_min
            if calibration_factor != 1.0:
                calibrated += 1
            ins = {
                "property_id": pid,
                "user_id": None,
                "chamgab_price": adj_price,
                "min_price": adj_min,
                "max_price": adj_max,
                "confidence": pred["confidence"],
            }
            res = sb.table("chamgab_analyses").insert(ins).execute()
            analysis_id = None
            if res.data and len(res.data) > 0:
                analysis_id = res.data[0].get("id")
            try:
                sb.table("chamgab_analysis_events").insert(
                    {
                        "property_id": pid,
                        "analysis_id": analysis_id,
                        "actor_user_id": None,
                        "status": "success",
                        "http_status": 200,
                        "request": {
                            "source": "batch_reanalyze_severe_gap",
                            "threshold": args.threshold,
                            "min_tx_price": args.min_tx_price,
                            "csv": str(csv_path.name),
                            "calibration_factor": calibration_factor,
                            "calibration_key": factor_key,
                            "at": datetime.now(timezone.utc).isoformat(),
                        },
                    }
                ).execute()
            except Exception:
                pass
            ok += 1
        except Exception as e:
            failed += 1
            try:
                sb.table("chamgab_analysis_events").insert(
                    {
                        "property_id": pid,
                        "analysis_id": None,
                        "actor_user_id": None,
                        "status": "error",
                        "http_status": 500,
                        "error_code": "BATCH_REANALYZE_ERROR",
                        "error_message": str(e)[:500],
                        "request": {
                            "source": "batch_reanalyze_severe_gap",
                            "threshold": args.threshold,
                            "min_tx_price": args.min_tx_price,
                            "csv": str(csv_path.name),
                            "calibration_factor": calibration_factor,
                            "calibration_key": factor_key,
                        },
                    }
                ).execute()
            except Exception:
                pass

        if idx % 200 == 0 or idx == len(target_ids):
            elapsed = time.time() - t0
            print(
                f"  progress {idx:,}/{len(target_ids):,} "
                f"(ok={ok:,}, failed={failed:,}, calibrated={calibrated:,}, elapsed={elapsed:.1f}s)"
            )
        if sleep_s > 0:
            time.sleep(sleep_s)

    elapsed = time.time() - t0
    print("Done.")
    print(
        f"  inserted={ok:,}, failed={failed:,}, calibrated={calibrated:,}, elapsed={elapsed:.1f}s"
    )
    summary = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "mode": "apply",
        "csv_path": str(csv_path),
        "threshold": args.threshold,
        "min_tx_price": float(args.min_tx_price),
        "targets": len(target_ids),
        "inserted": ok,
        "failed": failed,
        "calibrated_count": calibrated,
        "calibration": calibration,
        "elapsed_sec": round(elapsed, 1),
    }
    latest_summary_path = LOGS_DIR / "chamgab_reanalyze_summary_latest.json"
    latest_summary_path.write_text(
        json.dumps(summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(f"SUMMARY_JSON:{json.dumps(summary, ensure_ascii=False)}")
    # Treat partial success as success for batch operations.
    # Hard-fail only when nothing was inserted.
    if ok == 0 and failed > 0:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
